[project]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bdns-plus"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest"

[feature.docs.tasks]
build-docs = { cmd = "quarto build .", cwd = "docs" }

[dependencies]
frictionless = ">=5.18.0,<6"
pydantic = ">=2.10.6,<3"
annotated-types = ">=0.7.0,<0.8"
pytest = "*"
pydantic-extra-types = ">=2.10.2,<3"
pycountry = ">=24.6.1,<25"

[feature.docs.dependencies]
quarto = "*"

# [package.build]
# backend = { name = "pixi-build-python", version = "0.1.*" }
# channels = [
#   "https://prefix.dev/pixi-build-backends",
#   "https://prefix.dev/conda-forge",
# ]

# [package.host-dependencies]
# hatchling = "*"

[pypi-dependencies]
bdns_plus = { path = ".", editable = true }
