[project]
authors = [{name = "jgunstone", email = "j.gunstone@maxfordham.com"}]
dependencies = []
description = "Add a short description here"
name = "bdns-plus"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
bdns_plus = { path = ".", editable = true }

[tool.pixi.feature.docs.dependencies]
quarto = "*"

[tool.pixi.feature.package.dependencies]
hatch = "*"

[tool.pixi.environments]
docs = ["docs"]
package = {features = ["package"], no-default-feature = true}

[tool.pixi.tasks]
tests = "pytest"

[tool.pixi.feature.docs.tasks]
build-docs = { cmd = "quarto render .", cwd = "docs" }

[tool.pixi.feature.package.tasks]
build = "hatch build"
# publish = "hatch publish -u __token__ -a <your-pypi-token>"
# ship  = {depends-on = ["build", "publish"]}

[tool.pixi.dependencies]
frictionless = ">=5.18.0,<6"
pydantic = ">=2.10.6,<3"
annotated-types = ">=0.7.0,<0.8"
pytest = "*"
pydantic-extra-types = ">=2.10.2,<3"
pycountry = ">=24.6.1,<25"
pydantic-settings = ">=2.8.0,<3"


