[project]
authors = [{name = "jgunstone", email = "j.gunstone@maxfordham.com"}]
dependencies = []
description = "Add a short description here"
name = "bdns-plus"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
bdns_plus = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
frictionless = ">=5.18.0,<6"
pydantic = ">=2.10.6,<3"
annotated-types = ">=0.7.0,<0.8"
