project:
  type: website

website:
  navbar:
    left:
      - index.qmd
      - examples.qmd
      - compare-ifc4_3.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
