project:
  type: website

website:
  favicon: tag-solid.ico
  navbar:
    left:
      - index.qmd
      - volumes-and-levels.qmd
      - tags.py
      - customisations.py
      - serialisation.qmd
      - test.py
      - revit.qmd
      - text: "Examples"
        id: examples
        href: examples/index.html


    right:
      - text: "Notes"
        href: compare-ifc4_3.qmd
      - icon: github
        href: https://github.com/maxfordham/bdns-plus
        aria-label: GitHub


  sidebar:
    - id: examples
      # collapse-level: 2
      contents: 
        - examples/index.qmd
        - examples/custom-project-example.qmd
        # - text: "Examples"
        #   contents: examples/*

format:
  html:
    css: styles.css
    toc: true
    theme:
      light: flatly
      dark: darkly
