project:
  type: website

website:
  navbar:
    left:
      - index.qmd
      - summarise-default-config.qmd  
      - compare-ifc4_3.qmd
      - examples

    right:
      - icon: github
        href: https://github.com/maxfordham/document-issue
        aria-label: GitHub

  sidebar:
      - text: "Examples"
        contents: examples/*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
