project:
  type: website

website:
  title: "bdns_plus"
  navbar:
    left:
      - href: index.qmd
        text: bdns_plus
      - standard.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
