project:
  type: website

website:
  favicon: tag-solid.ico
  navbar:
    left:
      - index.qmd
      - default-tags.qmd
      - customisations.qmd
      - text: "Examples"
        href: examples/index.html

    right:
      - icon: github
        href: https://github.com/maxfordham/bdns-plus
        aria-label: GitHub
      - text: "Notes"
        href: compare-ifc4_3.qmd

  sidebar:
    - id: Examples
      collapse-level: 2
      contents:
        - text: "Examples"
          contents: examples/*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
