---
toc: true
title: BDNS-plus (WIP)
---

{{< var bdns >}} (Building Device Naming Syntax) ➕ **equipment tagging**.
`bdns-plus` is a superset of {{< var bdns >}}: extending BDNS to define a consistent and configurable approach to producing equipment references for Design Information (drawings, schedules, specifications).
It does so by defining metadata required for every item of equipment, from this metadata it is then possible to serialize a [BDNS compliant, machine read-able tag](https://theodi.github.io/BDNS/BDNS_Specification_naming_syntax.html#format-2),
as well a tag that clearly communicates the metadata in a format designed for improved human-legibility and compliance with project standards.

The key words `MUST`, `MUST NOT`, `REQUIRED`, `SHALL`, `SHALL NOT`, `SHOULD`, `SHOULD NOT`, `RECOMMENDED`, `MAY`, and `OPTIONAL` in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).

## Definition of Terms

- **project** - a construction project. It may be multi-stage and may have multiple buildings. The client will be the same and typically the project team will be the same.
- **volume** - a section of a project. A single building project typically has 1 volume. A multi-building project each building will be a volume. External landscaping may be a separate volume.
- **level** - a floor of a building. This `MAY`  include [mezzanine levels], see discussion.
- **type** - a specific type of equipment, i.e. an item with a defined model number that can ultimately be purchased.
- **instance** - a specific piece of equipment / asset within a project. Every asset is unique.
- **coming soon...** **system_type** - what system type a piece of equipment belongs to (e.g. a radiator would below to LTHW system type)
- **coming soon...** **system_id** - the specific system that a piece of equipment belongs to. For electrical systems this parameter
isn't used as typically all electrical appliances will connect back a common point (the utilities connection), but for
closed mechanical systems (e.g. LTHW systems) it is possible/common to have multiple distinct closed systems within a single project.

## Overview

A definition of the properties required for equipment tagging for the digital identification of equipment
for use in the design, construction and management of buildings.

It is designed to be an opinionated superset of the [BDNS](https://theodi.github.io/BDNS/) standard.
The focus of this standard is to simultaneously provide a unique, machine-readable identifier for each asset as well
as a human-readable and intuitive tag that can be used on drawings and other design information. Whilst the BDNS standard
`MAY` be used as is for equipment tagging on drawing and at later stages in asset management systems, the formation of the
`bdns_tag` is not consistent with many project drawing standards. This standard aims to consistently define the properties
that `MUST` be recorded for each asset, and from this information it `MUST` be possible to generate a compliant `bdns_tag`. 
The same properties `MUST` then be used to create a more flexible / human-readable `type_tag` and `instance_tag` for equipment references/tags on drawings.
Using this approach it is possible to apply BDNS a compliant methodology on a larger number of projects, improving standardisation and
leading to a potential value-add if the projects considers a BDNS compliant asset solution at the later stages of the project.

In simplest terms, this standard defines that for each item of equipment, its type must be defined and its approximate location must be defined.
The properties are used to: a) store valuable data about the item, b) create identification tags.
By definition, the mimumum information that `MUST` be recorded is:

| property name     | property type | description                                                                         |
|-------------------|---------------|-------------------------------------------------------------------------------------|
| abbreviation      | Type          | uppercase, alphabetic, 2-6 chars, indicates equipment type                          |
| type              | Type          | +ve integer. refers to a specific equipment type used within a project                          |
| volume            | Instance      | +ve integer. indicates the volume within a project the equipment is situated.                 |
| level             | Instance      | +ve integer. indicates the level within a project the equipment is situated                      |
| level_instance_id | Instance      | +ve integer. a numerical indentifyer for a specific piece of equipment within a volume and level | #TODO: volume_level_instance
| unique_instance_id| Instance      | +ve integer. calculated value from other instance parameters. used to create bdns tag            |



- **type** properties (`abbreviation` and `type`) would be the same for every identical item of equipment.
- **instance** properties (`volume`, `level` and `level_instance_id`) in combination with `abbreviation`,
`MUST` define a specific/unique instance of equipment within a project.
- `volume` and `level` integer properties may be mapped to more human-readable codes,
when this is done the mappings `MUST` be provided to the project teams.

Tagging properties are used to generate:

- a **type tag**. to indicate the type of a given asset/piece of equipment.
  - this is unique to the equipemnt type only, there may be many instances of this type in a building.
  - as an example, this is typically used on lighting layouts where many luminaires of the same type are used.
- a **instance tag**. this is `MUST` be unique to an individual asset within a project.
  - it is directly interchangeable with the bdns tag (and `MAY` be the same).
  - its focus is on legibility and ease of use for humans.
- a **BDNS tag**. this is `MUST` be unique to an individual asset within a project.
  - its focus is on legibility and ease of use for humans and machines.

## Type Tag

The `type_tag` is used to indicate the type of a given asset/piece of equipment on design information.
For a given `Type` of equipment, the combination of the `abbreviation` and `type` `MUST` be unique.
There `MAY` be many instances of eqipment of the same type within a project and therefore many indentical `type_tag`s.
The `type` and `abbreviation` `MUST` be combined without a delimiter to create a `unique_type_reference`.
Extra information about the equipment type `MAY` be stored in the `type_extra` property.
The `type_tag` `MUST` include the `unique_type_reference` and `MAY` include the `type_extra` field,
if `type_extra` is included it `MUST` be delimited from the `unique_type_reference` with a `type_extra_delimiter` character.

| property name         | property type | data type                       | description                                                                                              |
|-----------------------|---------------|---------------------------------|----------------------------------------------------------------------------------------------------------|
| unique_type_reference | Type          | uppercase alphabetic, 2-6 chars | combines `abbreviation` and `type` to create a `unique_type_reference`                                |
| type_extra            | Type          | string                          | used to indicate extra type information. e.g. `type_extra`="E" good indicate and emergency light fitting |
| type_extra_delimiter  | N/A           | string character                | used to delimit `unique_type_reference` and `type_extra`                                                 |
| type_tag              | Type          | string                          | `MUST` contain `unique_type_reference` and `MAY` contain `type_extra`                                    |

### `type_tag` Valid Implementations

- `type_tag` = `unique_type_reference`
- `type_tag` = `unique_type_reference` + `type_extra_delimiter` + `type_extra`

### `type_tag` Example

- `abbreviation` = `LT`, `type` = `1`, `type_extra` = `E`, `type_extra_delimiter` = `/`
  - => `unique_type_reference` = `LT1`
  - => `type_tag` = `LT1/E`
- `abbreviation` = `RAD`, `type` = `3`, `type_extra` = None, `type_extra_delimiter` = `/`
  - => `unique_type_reference` = `RAD3`
  - => `type_tag` = `RAD3`

## Instance Tag

The instance tag is used to indicate a specific instance of equipment within a project.
For a given unique item of equipment in a project, the `instance_tag` `MUST` be unique.
The `instance_tag` `SHOULD` indicate the equipment `abbreviation`, the volume, level and `level_instance_id`.
The `instance_tag` `MAY` be the same as the `bdns_tag`.

Extra information about the equipment instance `MAY` be stored in the `instance_extra` property.
For legibility, the `unique_instance_reference` `MAY` be formatted with a delimiter (`instance_tag_delimiter`) between the `abbreviation`, `volume_reference`, `level_reference` and `level_instance_id`.
The `unique_instance_reference` `MUST` serialisable / deserialisable to / from the `bdns_tag`.
The `instance_tag` `MUST` include the `unique_instance_reference` and `MAY` include the `instance_extra` field.
Where there is only 1no project volume, the `volume_reference` `MAY` be omitted from the `instance_tag`.

It is `RECOMMENDED` that when mapping the `level_id` to the `level_reference`, mezzanine levels are ignored.
This is because mezzanine levels are 1/2 levels, and there is no logical way to represent these in the `level_id` field which must be a positive integer.

| property name             | property type | data type         | description                                                                                                         |
|---------------------------|---------------|-------------------|---------------------------------------------------------------------------------------------------------------------|
| level_reference           | Instance      | string or integer | indicates the level. maps to the `level_id` field. -ve numbers and strings allowed.                                 |
| volume_reference          | Instance      | string or integer | unique reference to a given piece of equipment, which encodes type, level and volume                                |
| level_name                | Instance      | string            | combined with `abbreviation` creates a unique reference to an item of equipment                                     |
| volume_name               | Instance      | string            | unique reference to a given piece of equipment, which encodes type, level and volume                                |
| instance_tag_delimiter    | N/A           | string character  | used to delimit `abbreviation`, `volume_reference`, `level_reference` and `level_instance_id`                       |
| unique_instance_reference | Instance      | string            | combines `abbreviation`, volume, level and `level_instance_id` to create a unique reference to an item of equipment |
| instance_tag              | Instance      | string            | `unique_instance_reference`, and `MAY` also show `instance_extra` information                                       |
| instance_extra            | Instance      | string            | contains additional information about an instance. `MAY` be shown on `instance_tag`                                 |
| instance_extra_delimiter  | N/A           | string character  | used to delimit `unique_instance_reference` and `instance_extra`                                                    |

### `instance_tag` Valid Implementations

- `unique_instance_reference` = `abbreviation` + `instance_tag_delimiter` + `volume_reference` + `instance_tag_delimiter` + `level_reference` + `instance_tag_delimiter` + `level_instance_id`
- `instance_tag` = `unique_instance_reference` + `instance_extra_delimiter` + `instance_extra`

### `instance_tag` Example

- `abbreviation` = `LT`, `volume_id` = `1`, `level_id` = `0`, `level_instance_id` = `1`, `instance_extra` = `E`, `instance_extra_delimiter` = `/`, `instance_tag_delimiter` = `_`
  - => `volume_reference` = `A`, `level_reference` = `GF`
  - => `unique_instance_reference` = `LT/A/GF/1`
  - => `instance_tag` = `LT/A/GF/1_E`

## BDNS Tag

For a given `abbreviation`, the `volume_id`, `level_id` and `level_instance_id` `MUST` be combined to create a unique identifier (`instance_id`) for each piece of equipment.
NOTE. This unique number `MUST` be independent of the specific equipment type (`type`).

| property name | property type | data type        | description                                                                          |
|---------------|---------------|------------------|--------------------------------------------------------------------------------------|
| instance_id   | Instance      | positive integer | combined with `abbreviation` creates a unique reference to an item of equipment      |
| bdns_tag      | Instance      | string           | unique reference to a given piece of equipment, which encodes abbreviation, level and volume |

It `MUST` be possible to serialise and deserialise between [`volume_id`, `level_id` and `level_instance_id`] and [`instance_id`] to create a unique identifier for each piece of equipment.

It `SHOULD` be simple to a user interogating the `instance_id` how to determine the `volume_id`, `level_id` and `level_instance_id`.

- e.g. `instance_id` = `1001` would be `volume_id` = `1`, `level_id` = `0` and `level_instance_id` = `1`.

### `bdns_tag` Valid Implementations

- `bdns_tag` = `abbreviation` + "-" +  `instance_id`
- `bdns_tag` = `unique_type_reference` + "-" +  `instance_id`

### Equipment Specific Tagging Methodologies

Projects `SHOULD` define a method for tagging equipment that is consistent across all equipment types.
Projects `MAY` customise how the tag is constructed based on the equipment type if required.

## Project Configuration




## Related Work

- extends [BDNS (Building Device Naming Syntax)](https://theodi.github.io/BDNS/)
- formalises some of the logic outlined by [TheFridgeShaman](https://github.com/TheFridgeShaman) in [this discussion](https://github.com/theodi/BDNS/issues/154)